openapi: 3.0.3
info:
  title: Tekton Hub
  description: HTTP services for managing Tekton Hub
  version: "0.1"
servers:
- url: http://api.hub.tekton.dev
paths:
  /:
    get:
      tags:
      - status
      summary: Status status
      description: Return status 'ok' when the server has started successfully
      operationId: status#Status
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponseBody'
              example:
                status: ok
  /auth/login:
    post:
      tags:
      - auth
      summary: Authenticate auth
      description: Authenticates users against GitHub OAuth
      operationId: auth#Authenticate
      parameters:
      - name: code
        in: query
        description: OAuth Authorization code of User
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: OAuth Authorization code of User
          example: Sequi est dolor saepe odit.
        example: Et non nobis.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticateResponseBody'
              example:
                token: Ut aut quos distinctio ipsam eos.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "401":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "403":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /catalog/refresh:
    post:
      tags:
      - catalog
      summary: Refresh catalog
      description: Refresh the catalog for new resources
      operationId: catalog#Refresh
      responses:
        "200":
          description: ""
          content:
            application/json:
              example: {}
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /categories:
    get:
      tags:
      - category
      summary: list category
      description: List all categories along with their tags sorted by name
      operationId: category#list
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
                example:
                - id: 1
                  name: Image Builder
                  tags:
                  - id: 1
                    name: image-build
                  - id: 2
                    name: kaniko
                - id: 1
                  name: Image Builder
                  tags:
                  - id: 1
                    name: image-build
                  - id: 2
                    name: kaniko
              example:
              - id: 1
                name: Image Builder
                tags:
                - id: 1
                  name: image-build
                - id: 2
                  name: kaniko
              - id: 1
                name: Image Builder
                tags:
                - id: 1
                  name: image-build
                - id: 2
                  name: kaniko
              - id: 1
                name: Image Builder
                tags:
                - id: 1
                  name: image-build
                - id: 2
                  name: kaniko
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /query:
    get:
      tags:
      - resource
      summary: Query resource
      description: Find resources by a combination of name, kind and tags
      operationId: resource#Query
      parameters:
      - name: name
        in: query
        description: Name of resource
        allowEmptyValue: true
        schema:
          type: string
          description: Name of resource
          default: ""
          example: Iusto quis labore reprehenderit ut.
        example: Vero vel error nisi quam inventore et.
      - name: kinds
        in: query
        description: Kinds of resource to filter by
        allowEmptyValue: true
        schema:
          type: array
          items:
            type: string
            example: Maxime voluptas.
          description: Kinds of resource to filter by
          example:
          - Sed sapiente libero sit id.
          - Nam quia incidunt accusamus dolor non eum.
        example:
        - Et qui nam.
        - Esse enim sint tempora dolorem neque.
      - name: tags
        in: query
        description: Tags associated with a resource to filter by
        allowEmptyValue: true
        schema:
          type: array
          items:
            type: string
            example: Nesciunt sed debitis laboriosam.
          description: Tags associated with a resource to filter by
          example:
          - Asperiores reiciendis hic.
          - Beatae dicta itaque possimus.
          - Aut repellat.
        example:
        - Accusantium nulla ea rem aperiam.
        - Sapiente labore.
      - name: limit
        in: query
        description: Maximum number of resources to be returned
        allowEmptyValue: true
        schema:
          type: integer
          description: Maximum number of resources to be returned
          default: 100
          example: 15716303420227094745
        example: 1532180026290514679
      - name: match
        in: query
        description: Strategy used to find matching resources
        allowEmptyValue: true
        schema:
          type: string
          description: Strategy used to find matching resources
          default: contains
          example: exact
          enum:
          - exact
          - contains
        example: contains
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResponseWithoutVersionCollection'
              example:
              - catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
              - catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
              - catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /resource/{catalog}/{kind}/{name}:
    get:
      tags:
      - resource
      summary: ByCatalogKindName resource
      description: Find resources using name of catalog, resource name and kind of resource
      operationId: resource#ByCatalogKindName
      parameters:
      - name: catalog
        in: path
        description: name of catalog
        required: true
        schema:
          type: string
          description: name of catalog
          example: Iure eum et et nam pariatur corrupti.
        example: Odit expedita.
      - name: kind
        in: path
        description: kind of resource
        required: true
        schema:
          type: string
          description: kind of resource
          example: task
          enum:
          - task
          - pipeline
        example: pipeline
      - name: name
        in: path
        description: Name of resource
        required: true
        schema:
          type: string
          description: Name of resource
          example: Consequatur numquam id aut illum ut rerum.
        example: Consequatur quia at.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResponseWithoutVersionCollection'
              example:
              - catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
              - catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
              - catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /resource/{catalog}/{kind}/{name}/{version}:
    get:
      tags:
      - resource
      summary: ByCatalogKindNameVersion resource
      description: Find resource using name of catalog & name, kind and version of resource
      operationId: resource#ByCatalogKindNameVersion
      parameters:
      - name: catalog
        in: path
        description: name of catalog
        required: true
        schema:
          type: string
          description: name of catalog
          example: Suscipit fuga nam.
        example: Eveniet qui sint omnis consequatur omnis.
      - name: kind
        in: path
        description: kind of resource
        required: true
        schema:
          type: string
          description: kind of resource
          example: task
          enum:
          - task
          - pipeline
        example: task
      - name: name
        in: path
        description: name of resource
        required: true
        schema:
          type: string
          description: name of resource
          example: Voluptas animi molestiae nam quas veniam optio.
        example: Ut dolorum.
      - name: version
        in: path
        description: version of resource
        required: true
        schema:
          type: string
          description: version of resource
          example: Modi occaecati vitae ducimus ab natus autem.
        example: Id porro placeat et et at itaque.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ByCatalogKindNameVersionResponseBody'
              example:
                description: Buildah task builds source into a container image and then pushes it to a container registry.
                displayName: Buildah
                id: 1
                minPipelinesVersion: 0.12.1
                rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                resource:
                  catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                updatedAt: 2020-01-01 12:00:00 +0000 UTC
                version: "0.1"
                webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /resource/{id}:
    get:
      tags:
      - resource
      summary: ById resource
      description: Find a resource using it's id
      operationId: resource#ById
      parameters:
      - name: id
        in: path
        description: ID of a resource
        required: true
        schema:
          type: integer
          description: ID of a resource
          example: 7027495399998000197
        example: 10579553497869499435
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ByIDResponseBody'
              example:
                catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
                versions:
                - id: 1
                  version: "0.1"
                - id: 2
                  version: "0.2"
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /resource/{id}/rating:
    get:
      tags:
      - rating
      summary: Get rating
      description: Find user's rating for a resource
      operationId: rating#Get
      parameters:
      - name: id
        in: path
        description: ID of a resource
        required: true
        schema:
          type: integer
          description: ID of a resource
          example: 9030580309542282086
        example: 17404271294733310793
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResponseBody'
              example:
                rating: 8243725567479150691
        "401":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "403":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
      security:
      - jwt_header_Authorization:
        - rating:read
        - rating:write
    put:
      tags:
      - rating
      summary: Update rating
      description: Update user's rating for a resource
      operationId: rating#Update
      parameters:
      - name: id
        in: path
        description: ID of a resource
        required: true
        schema:
          type: integer
          description: ID of a resource
          example: 18412006956859135621
        example: 16296331032558935245
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRequestBody'
            example:
              rating: 3
      responses:
        "200":
          description: ""
          content:
            application/json:
              example: {}
        "401":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "403":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
      security:
      - jwt_header_Authorization:
        - rating:read
        - rating:write
  /resource/{id}/versions:
    get:
      tags:
      - resource
      summary: VersionsByID resource
      description: Find all versions of a resource by its id
      operationId: resource#VersionsByID
      parameters:
      - name: id
        in: path
        description: ID of a resource
        required: true
        schema:
          type: integer
          description: ID of a resource
          example: 1541791016618738007
        example: 17090987381425625275
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Versions'
              example:
                latest:
                  id: 2
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
                  version: "0.2"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
                versions:
                - id: 1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                - id: 2
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
                  version: "0.2"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
  /resource/version/{versionID}:
    get:
      tags:
      - resource
      summary: ByVersionId resource
      description: Find a resource using its version's id
      operationId: resource#ByVersionId
      parameters:
      - name: versionID
        in: path
        description: Version ID of a resource's version
        required: true
        schema:
          type: integer
          description: Version ID of a resource's version
          example: 5057203540763806787
        example: 9293410832204462916
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ByCatalogKindNameVersionResponseBody'
              example:
                description: Buildah task builds source into a container image and then pushes it to a container registry.
                displayName: Buildah
                id: 1
                minPipelinesVersion: 0.12.1
                rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                resource:
                  catalog:
                    id: 1
                    type: community
                  id: 1
                  kind: task
                  name: buildah
                  rating: 4.3
                  tags:
                  - id: 1
                    name: image-build
                updatedAt: 2020-01-01 12:00:00 +0000 UTC
                version: "0.1"
                webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        "404":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
  /resources:
    get:
      tags:
      - resource
      summary: List resource
      description: List all resources sorted by rating and name
      operationId: resource#List
      parameters:
      - name: limit
        in: query
        description: Maximum number of resources to be returned
        allowEmptyValue: true
        schema:
          type: integer
          description: Maximum number of resources to be returned
          default: 100
          example: 4419648050839368861
        example: 8257605382696551331
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResponseWithoutVersionCollection'
              example:
              - catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
              - catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
              - catalog:
                  id: 1
                  type: community
                id: 1
                kind: task
                latestVersion:
                  description: Buildah task builds source into a container image and then pushes it to a container registry.
                  displayName: Buildah
                  id: 1
                  minPipelinesVersion: 0.12.1
                  rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
                  updatedAt: 2020-01-01 12:00:00 +0000 UTC
                  version: "0.1"
                  webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
                name: buildah
                rating: 4.3
                tags:
                - id: 1
                  name: image-build
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    AuthenticateResponseBody:
      type: object
      properties:
        token:
          type: string
          description: JWT
          example: Architecto quia beatae sed sit voluptas.
      example:
        token: Voluptatem fugiat corrupti rem dolorum ducimus tempora.
      required:
      - token
    ByCatalogKindNameVersionResponseBody:
      type: object
      properties:
        description:
          type: string
          description: Description of version
          example: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName:
          type: string
          description: Display name of version
          example: Buildah
        id:
          type: integer
          description: ID is the unique id of resource's version
          example: 1
        minPipelinesVersion:
          type: string
          description: Minimum pipelines version the resource's version is compatible with
          example: 0.12.1
        rawURL:
          type: string
          description: Raw URL of resource's yaml file of the version
          example: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          format: uri
        resource:
          $ref: '#/components/schemas/Resource2'
        updatedAt:
          type: string
          description: Timestamp when version was last updated
          example: 2020-01-01 12:00:00 +0000 UTC
          format: date-time
        version:
          type: string
          description: Version of resource
          example: "0.1"
        webURL:
          type: string
          description: Web URL of resource's yaml file of the version
          example: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          format: uri
      description: ByCatalogKindNameVersionResponseBody result type (default view)
      example:
        description: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName: Buildah
        id: 1
        minPipelinesVersion: 0.12.1
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        resource:
          catalog:
            id: 1
            type: community
          id: 1
          kind: task
          name: buildah
          rating: 4.3
          tags:
          - id: 1
            name: image-build
        updatedAt: 2020-01-01 12:00:00 +0000 UTC
        version: "0.1"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      required:
      - id
      - version
      - displayName
      - description
      - minPipelinesVersion
      - rawURL
      - webURL
      - updatedAt
      - resource
    ByIDResponseBody:
      type: object
      properties:
        catalog:
          $ref: '#/components/schemas/Catalog'
        id:
          type: integer
          description: ID is the unique id of the resource
          example: 1
        kind:
          type: string
          description: Kind of resource
          example: task
        latestVersion:
          $ref: '#/components/schemas/Version'
        name:
          type: string
          description: Name of resource
          example: buildah
        rating:
          type: number
          description: Rating of resource
          example: 4.3
          format: double
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: Tags related to resource
          example:
          - id: 1
            name: image-build
        versions:
          type: array
          items:
            $ref: '#/components/schemas/Version3'
          description: List of all versions of a resource
          example:
          - id: 1
            version: "0.1"
          - id: 2
            version: "0.2"
      description: ByIdResponseBody result type (default view)
      example:
        catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        versions:
        - id: 1
          version: "0.1"
        - id: 2
          version: "0.2"
      required:
      - id
      - name
      - catalog
      - kind
      - latestVersion
      - tags
      - rating
      - versions
    Catalog:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of the catalog
          example: 1
        name:
          type: string
          description: Name of catalog
          example: Tekton
        type:
          type: string
          description: Type of catalog
          example: community
          enum:
          - official
          - community
      example:
        id: 1
        name: Tekton
        type: community
      required:
      - id
      - name
      - type
    Category:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of the category
          example: 1
        name:
          type: string
          description: Name of category
          example: Image Builder
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: List of tags associated with the category
          example:
          - id: 1
            name: image-build
          - id: 2
            name: kaniko
      example:
        id: 1
        name: Image Builder
        tags:
        - id: 1
          name: image-build
        - id: 2
          name: kaniko
      required:
      - id
      - name
      - tags
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      description: Internal Server Error
      example:
        fault: false
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: true
        timeout: true
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    GetResponseBody:
      type: object
      properties:
        rating:
          type: integer
          description: User rating for resource
          example: 3663290079815088214
          format: int64
      example:
        rating: 5709739823626364892
      required:
      - rating
    Resource:
      type: object
      properties:
        catalog:
          $ref: '#/components/schemas/Catalog'
        id:
          type: integer
          description: ID is the unique id of the resource
          example: 1
        kind:
          type: string
          description: Kind of resource
          example: task
        latestVersion:
          $ref: '#/components/schemas/Version2'
        name:
          type: string
          description: Name of resource
          example: buildah
        rating:
          type: number
          description: Rating of resource
          example: 4.3
          format: double
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: Tags related to resource
          example:
          - id: 1
            name: image-build
        versions:
          type: array
          items:
            $ref: '#/components/schemas/Version2'
          description: List of all versions of a resource
          example:
          - id: 1
            version: "0.1"
          - id: 2
            version: "0.2"
      description: The resource type describes resource information.
      example:
        catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
        versions:
        - id: 1
          version: "0.1"
        - id: 2
          version: "0.2"
      required:
      - id
      - name
      - catalog
      - kind
      - latestVersion
      - tags
      - rating
      - versions
    Resource2:
      type: object
      properties:
        catalog:
          $ref: '#/components/schemas/Catalog'
        id:
          type: integer
          description: ID is the unique id of the resource
          example: 1
        kind:
          type: string
          description: Kind of resource
          example: task
        name:
          type: string
          description: Name of resource
          example: buildah
        rating:
          type: number
          description: Rating of resource
          example: 4.3
          format: double
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: Tags related to resource
          example:
          - id: 1
            name: image-build
      description: The resource type describes resource information.
      example:
        catalog:
          id: 1
          type: community
        id: 1
        kind: task
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
      required:
      - id
      - name
      - catalog
      - kind
      - latestVersion
      - tags
      - rating
      - versions
    ResourceResponseWithoutVersion:
      type: object
      properties:
        catalog:
          $ref: '#/components/schemas/Catalog'
        id:
          type: integer
          description: ID is the unique id of the resource
          example: 1
        kind:
          type: string
          description: Kind of resource
          example: task
        latestVersion:
          $ref: '#/components/schemas/Version'
        name:
          type: string
          description: Name of resource
          example: buildah
        rating:
          type: number
          description: Rating of resource
          example: 4.3
          format: double
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: Tags related to resource
          example:
          - id: 1
            name: image-build
      description: The resource type describes resource information. (withoutVersion view)
      example:
        catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
      required:
      - id
      - name
      - catalog
      - kind
      - latestVersion
      - tags
      - rating
    ResourceResponseWithoutVersionCollection:
      type: array
      items:
        $ref: '#/components/schemas/ResourceResponseWithoutVersion'
      description: QueryResponseBody is the result type for an array of ResourceResponse (withoutVersion view)
      example:
      - catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
      - catalog:
          id: 1
          type: community
        id: 1
        kind: task
        latestVersion:
          description: Buildah task builds source into a container image and then pushes it to a container registry.
          displayName: Buildah
          id: 1
          minPipelinesVersion: 0.12.1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          updatedAt: 2020-01-01 12:00:00 +0000 UTC
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        name: buildah
        rating: 4.3
        tags:
        - id: 1
          name: image-build
    StatusResponseBody:
      type: object
      properties:
        status:
          type: string
          description: Status of server
          example: ok
      example:
        status: ok
      required:
      - status
    Tag:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of tag
          example: 1
        name:
          type: string
          description: Name of tag
          example: image-build
      example:
        id: 1
        name: image-build
      required:
      - id
      - name
    UpdateRequestBody:
      type: object
      properties:
        rating:
          type: integer
          description: User rating for resource
          example: 2
          minimum: 0
          maximum: 5
      example:
        rating: 2
      required:
      - rating
    Version:
      type: object
      properties:
        description:
          type: string
          description: Description of version
          example: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName:
          type: string
          description: Display name of version
          example: Buildah
        id:
          type: integer
          description: ID is the unique id of resource's version
          example: 1
        minPipelinesVersion:
          type: string
          description: Minimum pipelines version the resource's version is compatible with
          example: 0.12.1
        rawURL:
          type: string
          description: Raw URL of resource's yaml file of the version
          example: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          format: uri
        updatedAt:
          type: string
          description: Timestamp when version was last updated
          example: 2020-01-01 12:00:00 +0000 UTC
          format: date-time
        version:
          type: string
          description: Version of resource
          example: "0.1"
        webURL:
          type: string
          description: Web URL of resource's yaml file of the version
          example: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          format: uri
      description: The Version result type describes resource's version information.
      example:
        description: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName: Buildah
        id: 1
        minPipelinesVersion: 0.12.1
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        updatedAt: 2020-01-01 12:00:00 +0000 UTC
        version: "0.1"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      required:
      - id
      - version
      - displayName
      - description
      - minPipelinesVersion
      - rawURL
      - webURL
      - updatedAt
      - resource
    Version2:
      type: object
      properties:
        description:
          type: string
          description: Description of version
          example: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName:
          type: string
          description: Display name of version
          example: Buildah
        id:
          type: integer
          description: ID is the unique id of resource's version
          example: 1
        minPipelinesVersion:
          type: string
          description: Minimum pipelines version the resource's version is compatible with
          example: 0.12.1
        rawURL:
          type: string
          description: Raw URL of resource's yaml file of the version
          example: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          format: uri
        resource:
          $ref: '#/components/schemas/Resource'
        updatedAt:
          type: string
          description: Timestamp when version was last updated
          example: 2020-01-01 12:00:00 +0000 UTC
          format: date-time
        version:
          type: string
          description: Version of resource
          example: "0.1"
        webURL:
          type: string
          description: Web URL of resource's yaml file of the version
          example: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          format: uri
      description: The Version result type describes resource's version information.
      example:
        description: Buildah task builds source into a container image and then pushes it to a container registry.
        displayName: Buildah
        id: 1
        minPipelinesVersion: 0.12.1
        rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
        resource:
          catalog:
            id: 1
            type: community
          id: 1
          kind: task
          name: buildah
          rating: 4.3
          tags:
          - id: 1
            name: image-build
        updatedAt: 2020-01-01 12:00:00 +0000 UTC
        version: "0.1"
        webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
      required:
      - id
      - version
      - displayName
      - description
      - minPipelinesVersion
      - rawURL
      - webURL
      - updatedAt
      - resource
    Version3:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of resource's version
          example: 1
        version:
          type: string
          description: Version of resource
          example: "0.1"
      description: The Version result type describes resource's version information.
      example:
        id: 1
        version: "0.1"
      required:
      - id
      - version
      - displayName
      - description
      - minPipelinesVersion
      - rawURL
      - webURL
      - updatedAt
      - resource
    Versions:
      type: object
      properties:
        latest:
          $ref: '#/components/schemas/Version2'
        versions:
          type: array
          items:
            $ref: '#/components/schemas/Version2'
          description: List of all versions of resource
          example:
          - id: 1
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
            version: "0.1"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
          - id: 2
            rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
            version: "0.2"
            webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
      example:
        latest:
          id: 2
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
          version: "0.2"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
        versions:
        - id: 1
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.1/buildah.yaml
          version: "0.1"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml
        - id: 2
          rawURL: https://raw.githubusercontent.com/tektoncd/catalog/master/task/buildah/0.2/buildah.yaml
          version: "0.2"
          webURL: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml
      required:
      - latest
      - versions
  securitySchemes:
    jwt_header_Authorization:
      type: http
      description: Secures endpoint by requiring a valid JWT retrieved via the /auth/login endpoint.
      scheme: bearer
