swagger: "2.0"
info:
  title: Tekton Hub
  description: HTTP services for managing Tekton Hub
  version: "0.1"
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /categories:
    get:
      tags:
      - category
      summary: list category
      description: List all categories along with their tags sorted by name
      operationId: category#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/CategoryResponse'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/CategoryListInternalErrorResponseBody'
      schemes:
      - http
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  CategoryListInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  CategoryResponse:
    title: CategoryResponse
    type: object
    properties:
      id:
        type: integer
        description: ID is the unique id of the category
        example: 1
        format: int64
      name:
        type: string
        description: Name of category
        example: Image Builder
      tags:
        type: array
        items:
          $ref: '#/definitions/TagResponse'
        description: List of tags associated with the category
        example:
        - id: 1
          name: image-build
        - id: 2
          name: kaniko
    example:
      id: 1
      name: Image Builder
      tags:
      - id: 1
        name: image-build
      - id: 2
        name: kaniko
    required:
    - id
    - name
    - tags
  TagResponse:
    title: TagResponse
    type: object
    properties:
      id:
        type: integer
        description: ID is the unique id of tag
        example: 1
        format: int64
      name:
        type: string
        description: Name of tag
        example: image-build
    example:
      id: 1
      name: image-build
    required:
    - id
    - name
